title: Posts
description: Personal Projects and News
author: Keith Nicholson's Blog
github: https://github.com/violentcat
about: Coder, mainly using C/C++. Rendering, emulation and more. I like making things.
disqus_shortname: ""
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/keffer"
    - icon: fa-linkedin
      link: "https://uk.linkedin.com/in/keith-nicholson-81375595"
    - icon: fa-github
      link: "https://github.com/violentcat"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "http://violentcat.co.uk"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
